export const CHARACTERS = {
    ATTACK: 'CHARACTERS.ATTACK',
    CREATE: 'CHARACTERS.CREATE',
    GAIN_XP: 'CHARACTERS.GAIN_XP',
    HEAL: 'CHARACTERS.HEAL',
    LEVEL_UP: 'CHARACTERS.LEVEL_UP',
    MOVE: 'CHARACTERS.MOVE',
}
