export const CHARACTERS = {
    ATTACK: 'CHARACTERS.ATTACK',
    CHECK: "CHARACTERS.CHECK",
    CREATE: 'CHARACTERS.CREATE',
    ORDER: "CHARACTERS.ORDER",
    INITIATIVE: 'CHARACTERS.INITIATIVE',
    // GAIN_XP: 'CHARACTERS.GAIN_XP',
    // HEAL: 'CHARACTERS.HEAL',
    // LEVEL_UP: 'CHARACTERS.LEVEL_UP',
    // MOVE: 'CHARACTERS.MOVE',
}

export const GAME = {
    FIGHT: 'GAME.FIGHT',
    READY: 'GAME.READY',
    START: 'GAME.START',
    ROUND: "GAME.ROUND",
    INITIATIVE: "GAME.INITIATIVE",
    NEXT: "GAME.NEXT",
    END: "GAME.END"
}
